import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { sassPlugin } from 'esbuild-sass-plugin';
import copyStaticFiles from 'esbuild-copy-static-files';
import path from 'path';
import packageJson from './package.json' with { type: 'json' };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Always build to ./dist/ - no vault path baked into the build tool. Point
// your local dev vault's plugin folder at this directory with a one-time
// symlink instead (see REFACTOR-DECISIONS.md's disposable-dev-vault entry
// for the convention). This used to be a ternary pointing `dev` mode at a
// hard-coded Windows path for one specific machine - and a stale one, at
// that; it pointed at a different, previous plugin's folder entirely
// (obsidian-canvas-dailynote). Every other dev/prod distinction (sourcemaps,
// NODE_ENV, watch-vs-rebuild below) still branches on `prod` as before -
// only the output *location* is no longer conditional.
const outdir = './dist/';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts', 'styles.scss'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	// Settled against Obsidian's actual runtime floor rather than left as an
	// arbitrary older number: desktop currently ships Electron 43.x (modern
	// V8), but Obsidian's Electron/'installer' version is decoupled from the
	// app's own auto-updater and can lag behind on machines that haven't
	// been manually reinstalled in a while - so 'current Electron' isn't a
	// safe floor to target. Mobile is a WKWebView (iOS, tied to device OS
	// version) or system WebView (Android) via Capacitor, not Electron at
	// all; Obsidian's own plugin docs flag that some JS engine features
	// aren't available until specific iOS versions (e.g. regex lookbehind
	// needs iOS 16.4+), confirming real fragmentation exists in the wild.
	// ES2020 is the floor: broadly supported for years across any realistic
	// Electron build and mobile WebView, and it's what the source already
	// assumes throughout (optional chaining, nullish coalescing are used
	// pervasively already). Matches tsconfig.json's target/lib exactly -
	// esbuild only downlevels syntax, not missing runtime APIs, so the two
	// numbers agreeing is what 'confirmed compatible' actually means here.
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minifySyntax: true,
	plugins: [
		sassPlugin(),
		copyStaticFiles({
			src: './manifest.json',
			dest: path.join(outdir, 'manifest.json'),
		}),
	],
	outdir: outdir,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		'process.env.PLUGIN_VERSION': `'${ packageJson.version }'`,
		'process.env.EMULATE_MOBILE': prod
			? 'false'
			: process.argv.includes('--mobile').toString(),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	await context.serve(); // This enables the 'live reload'
}